import asyncio
import os

CLASSIFY_CONCURRENCY = int(os.getenv("CLASSIFY_CONCURRENCY", "5"))
EXTRACT_CONCURRENCY = int(os.getenv("EXTRACT_CONCURRENCY", "2"))
BLUEPRINT_CONCURRENCY = int(os.getenv("BLUEPRINT_CONCURRENCY", "3"))

CLASSIFY_SEMAPHORE = asyncio.Semaphore(CLASSIFY_CONCURRENCY)
EXTRACT_SEMAPHORE = asyncio.Semaphore(EXTRACT_CONCURRENCY)
BLUEPRINT_SEMAPHORE = asyncio.Semaphore(BLUEPRINT_CONCURRENCY)
