"""add_jobs_and_job_submissions_tables

Revision ID: 38304ce6f51f
Revises: 408b7de0a798
Create Date: 2026-07-13 15:48:00.051575
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision = '38304ce6f51f'
down_revision = '408b7de0a798'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'finished', 'cancelled', name='job_status'), server_default='queued', nullable=False),
    sa.Column('result', sa.Enum('success', 'partial_success', 'failed', name='job_result'), nullable=True),
    sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('parent_job_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_student_id'), 'jobs', ['student_id'], unique=False)
    op.create_table('job_submissions',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', name='job_submission_item_status'), server_default='pending', nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['document_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'submission_id')
    )
    op.create_index(op.f('ix_job_submissions_job_id'), 'job_submissions', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_submissions_status'), 'job_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_job_submissions_submission_id'), 'job_submissions', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_submissions_submission_id'), table_name='job_submissions')
    op.drop_index(op.f('ix_job_submissions_status'), table_name='job_submissions')
    op.drop_index(op.f('ix_job_submissions_job_id'), table_name='job_submissions')
    op.drop_table('job_submissions')
    op.drop_index(op.f('ix_jobs_student_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###

