"""Add snapshot_fields_json to school_year_requirements

Revision ID: 408b7de0a798
Revises: 20260703_add_user_image_url
Create Date: 2026-07-10 21:15:25.953527
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '408b7de0a798'
down_revision = '20260703_add_user_image_url'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_adviser_invitations_clerk_invitation_id', 'adviser_invitations', type_='unique')
    op.drop_index('ix_document_submission_history_created_at', table_name='document_submission_history')
    op.drop_index('ix_document_submissions_parent', table_name='document_submissions')
    op.drop_index('ix_document_submissions_status', table_name='document_submissions')
    op.drop_column('document_submissions', 'llama_job_id')
    op.drop_index('ix_notifications_recipient_created_at', table_name='notifications')
    op.drop_index('ix_notifications_recipient_is_read', table_name='notifications')
    op.add_column('school_year_requirements', sa.Column('snapshot_fields_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('uq_school_years_name', 'school_years', type_='unique')
    op.drop_index('ux_school_years_one_active', table_name='school_years', postgresql_where='(is_active = true)')
    op.drop_index('ix_school_years_name', table_name='school_years')
    op.create_index(op.f('ix_school_years_name'), 'school_years', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_years_name'), table_name='school_years')
    op.create_index('ix_school_years_name', 'school_years', ['name'], unique=False)
    op.create_index('ux_school_years_one_active', 'school_years', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_unique_constraint('uq_school_years_name', 'school_years', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('school_year_requirements', 'snapshot_fields_json')
    op.create_index('ix_notifications_recipient_is_read', 'notifications', ['recipient_id', 'is_read'], unique=False)
    op.create_index('ix_notifications_recipient_created_at', 'notifications', ['recipient_id', 'created_at'], unique=False)
    op.add_column('document_submissions', sa.Column('llama_job_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_document_submissions_status', 'document_submissions', ['status'], unique=False)
    op.create_index('ix_document_submissions_parent', 'document_submissions', ['parent_submission_id'], unique=False)
    op.create_index('ix_document_submission_history_created_at', 'document_submission_history', ['created_at'], unique=False)
    op.create_unique_constraint('uq_adviser_invitations_clerk_invitation_id', 'adviser_invitations', ['clerk_invitation_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###

