"""adviser program assignment schema

Revision ID: 59f02132afc1
Revises: 1b17ca15eb0c
Create Date: 2026-04-12 20:19:44.450863
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision = '59f02132afc1'
down_revision = '1b17ca15eb0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_table('program_adviser_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('adviser_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adviser_id'], ['advisers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_adviser_assignments_id'), 'program_adviser_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_advisers_id'), 'advisers', ['id'], unique=False)
    op.drop_column('advisers', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advisers', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_advisers_id'), table_name='advisers')
    op.drop_index(op.f('ix_program_adviser_assignments_id'), table_name='program_adviser_assignments')
    op.drop_table('program_adviser_assignments')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
